### ISSUE TITLE
README.md mistake

### ISSUE THREAD

**Issue by radi-cho** [redux-book/code-samples#1]
Hello! I'm big fan of this book! But today I saw one VERY small bug with your markdown in README.md 
![image](https://cloud.githubusercontent.com/assets/12954909/24610064/dea620c4-1885-11e7-8035-025b3396f65e.png)
Please fix it! :smile: 
[Pull request here](https://github.com/redux-book/code-samples/pull/2)

**Comment by borisd** [comment]
Thanks!
