### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by nicubarbaros** [redux-book/code-samples#3]
The book is great so far, however,  I would love to come on Github and see the final code for the project as it was in the books. 
So I am getting a CORS error at first application
Error: 

`Fetch API cannot load https://s3.amazonaws.com/500tech-shared/db.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I added `{mode: 'cors}` but still the error persists.

**Comment by radi-cho** [comment]
@nicubarbaros Hello!
Maybe I can to help you, but I don't understand that error at all...
Please send something like _"piece"_ of your code and any more details :smile: :smile: :smile:

**Comment by borisd** [comment]
Hi, should be solved in latest version (now using local json file instead of real network access)

**Comment by radi-cho** [comment]
Thanks @borisd
