### ISSUE TITLE
Chapter 2

### ISSUE THREAD

**Issue by JasonSooter** [redux-book/code-samples#4]
Do you happen to have the completed code for chapter 2 using your Starter code with Webpack, etc? The book doesn't seem to follow the code samples in this repo.

Great book so far!

Thanks!

**Comment by TomJRodrigues** [comment]
Agreed. Things like page 33:

> Setting Up the Store
> We will start by creating the store. In Redux there is only one store, which is created and initialized by the createStore() method. Let’s open our index.js file and create the store

There is no mention of `index.js` before. With the previous amount of hand-holding I would have expected it to say "create index.js" or `touch index.js` in the terminal.

And just generally it doesn't look like this repo is in sync with the book so far. The last mention of `reducers.js` on page 39 in chapter 2 doesn't match with the repo currently, but it's uhhh...close?

**Comment by borisd** [comment]
Hi

We are working on an update from all the excellent feedback we got from the community. Hope to push a revised book and repo soon.

Thanks again!

**Comment by hanorine** [comment]
i gather from the update work that you might also be aware of the missing addRecipe action creator. It is imported and used but never actually implemented.

**Comment by borisd** [comment]
Hi @JaysQubeXon, missed your update on the PR.

Not sure what you mean, `addRecipe()` is defined in https://github.com/redux-book/code-samples/blob/master/2.first-application/action-creators.js#L2

**Comment by aidan-n** [comment]
Page 27 of the book says to write code in the index.js file. 

There are actually two files I found with this name, in the downloadable content. One is in starter/node_modules/indexes-of, and the other is in starter/node_modules/indexof. 

Where do we write this code?
