### ISSUE TITLE
Typo in Middleware code

### ISSUE THREAD

**Issue by TomJRodrigues** [redux-book/code-samples#5]
Chapter 10 on Middleware, page 163.

Previous page on Async Actions talked about waiting 500ms for an autocomplete action, code reflects only 50ms:

`20ms: dispatch({ type: 'AUTO_COMPLETE', payload: 'cat', meta: { debounce: 50 }}; 
// Suppressed`
`50ms:
// The action with payload 'cat' is dispatched by the middleware.`

**Comment by borisd** [comment]
Hi

Good catch, I am updating the book to reflect "500ms".

Thanks!
