### ISSUE TITLE
Why no code for chapter 3?

### ISSUE THREAD

**Issue by Muzietto** [redux-book/code-samples#6]
Normalising state is very important and complicated. The book code examples in chapter 3 fly over A LOT of details and here in GitHub there is not a single line of code!!
Asking 32$ for a book without complete code samples is outrageous!
Please publish ASAP a complete, working example of the code for chapter 3.

**Comment by oldmill1** [comment]
+1, any updates? Maybe even flushing out the `booksReducer` a bit more is all that's needed.

**Comment by borisd** [comment]
Hi

There is a simple example of normalization in https://github.com/redux-book/code-samples/tree/master/3.state-management 

For a comprehensive solution, we suggest using the https://github.com/paularmstrong/normalizr library. It has extensive documentation on how to normalize complex data structures.
